exclude: ["local"]
url: http://rainzhao.com
permalink: /:categories/:year/:title.html
gems:
  - jekyll-last-modified-at
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]