exclude: ["local"]
url: http://www.echochio.nctu.me
permalink: /:categories/:year/:title.html
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "no_intra_emphasis", "tables", "autolink", "strikethrough"]
